define [
  'jquery'
  'backbone'
  'views/building'
], ($, Backbone, BuildingView) ->
  'use strict'
  BuildingRouter = Backbone.Router.extend(routes:
    'buildings': 'viewBuildings')
  buildingView = new BuildingView

  initialize = ->
    router = new BuildingRouter
    router.on 'route:viewBuildings', ->
      console.log "inside the building router", "@", @
      buildingView.render()
      return
    console.log 'initializing the backbone history'
    Backbone.history.start()
    router

  initialize()
  # return {
  #  	initialize: initialize
  # };

# ---
# generated by js2coffee 2.0.0